const state={snapshot:null};
const $=id=>document.getElementById(id);
const key=prefix=>`${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
async function api(path,options={}){const response=await fetch(path,{headers:{"Content-Type":"application/json"},...options});const data=await response.json();if(!response.ok){const error=new Error(data.detail||"请求失败");error.details=data.details||[];throw error}return data}
function notify(message,error=false){const node=$("notice");node.textContent=message;node.className=error?"error":"ok";setTimeout(()=>node.className="",3500)}
function command(extra={}){return{expectedVersion:state.snapshot.dossier.version,actor:state.snapshot.dossier.leadRecorder,idempotencyKey:key("ui"),...extra}}
async function loadList(){try{const items=await api("/api/v1/dossiers?limit=50");const list=$("dossierList");list.className=items.length?"list":"list empty";list.innerHTML=items.length?items.map(d=>`<div class="item"><div><strong>${escapeHTML(d.trenchCode)}</strong><small>${escapeHTML(d.excavationArea)} · ${statusName(d.status)} · v${d.version}</small></div><button data-open="${d.id}">打开</button></div>`).join(""):"暂无案卷"}catch(e){notify(e.message,true)}}
async function openDossier(id){try{state.snapshot=await api(`/api/v1/dossiers/${id}`);render()}catch(e){notify(e.message,true)}}
function render(){const s=state.snapshot;if(!s)return;$("workspace").hidden=false;$("dossierTitle").textContent=`${s.dossier.trenchCode} · ${s.dossier.excavationArea}`;$("statusChip").textContent=statusName(s.dossier.status);$("versionLabel").textContent=`状态版本 v${s.dossier.version}`;$("unitCount").textContent=s.units.length;$("relationCount").textContent=s.relations.length;$("findingCount").textContent=s.findings.filter(f=>f.status==="open").length;renderUnits(s);renderRelations(s);renderCheckBatches(s);renderReview(s);renderCredentials(s);renderAudit(s);setActions(s)}
function unitOptions(s){return s.units.map(u=>`<option value="${u.id}">${escapeHTML(u.unitCode)}</option>`).join("")}
function renderUnits(s){$("unitList").innerHTML=s.units.map(u=>`<div class="item"><div><strong>${escapeHTML(u.unitCode)} · ${escapeHTML(u.unitType)}</strong><small>修订 ${u.revision} · ${u.topElevation}—${u.bottomElevation} m · ${escapeHTML(u.soilTraits)}</small></div><button data-edit-unit="${u.id}">修订</button></div>`).join("")||"<p class='muted'>尚无单位</p>";document.querySelectorAll("#relationForm select[name$='UnitId'],#pathForm select[name$='UnitId']").forEach(n=>n.innerHTML=unitOptions(s))}
function renderRelations(s){const units=Object.fromEntries(s.units.map(u=>[u.id,u.unitCode]));$("relationList").innerHTML=s.relations.map(r=>`<div class="item"><div><strong>${escapeHTML(units[r.sourceUnitId]||r.sourceUnitId)} ${relationName(r.relationType)} ${escapeHTML(units[r.targetUnitId]||r.targetUnitId)}</strong><small>修订 ${r.revision} · ${escapeHTML(r.evidenceNote)}</small></div><button data-edit-relation="${r.id}">替换</button></div>`).join("")||"<p class='muted'>尚无关系</p>"}
function renderCheckBatches(s){const select=$("checkBatchSelect"),selected=select.value;select.innerHTML=(s.checkBatches||[]).map((b,i)=>`<option value="${b.id}">第 ${i+1} 批 · v${b.dossierVersion} · 严重 ${b.errorCount}/提醒 ${b.warningCount}</option>`).join("");if(selected&&[...select.options].some(o=>o.value===selected))select.value=selected;else if(select.options.length)select.selectedIndex=select.options.length-1;renderFindings(s)}
function renderFindings(s){const node=$("findingList"),batches=s.checkBatches||[];if(!batches.length){node.className="list empty";node.textContent="尚未执行检查";return}const batch=batches.find(b=>b.id===$("checkBatchSelect").value)||batches[batches.length-1],change=$("changeFilter").value,severity=$("severityFilter").value;const findings=[...(batch.findings||[]),...(batch.resolved||[])].filter(f=>(!change||f.changeType===change)&&(!severity||f.severity===severity));if(!findings.length){node.className="list empty";node.textContent="该筛选下没有问题";return}node.className="list";node.innerHTML=findings.map(f=>`<div class="item finding ${f.severity}"><div><strong>${f.ruleCode} · ${f.severity==="error"?"严重":"提醒"} · ${changeName(f.changeType)}</strong><small>${escapeHTML(f.message)}${f.resolutionNote?` · 整改：${escapeHTML(f.resolutionNote)}`:""}${f.triggerRevisions?.length?` · 触发：${escapeHTML(f.triggerRevisions.join("、"))}`:""}</small></div>${f.changeType!=="resolved"&&f.status==="open"&&batch.id===s.lastCheckRunId?`<button data-resolve="${f.id}">记录整改</button>`:"<span>已关闭/消除</span>"}</div>`).join("")}
function renderReview(s){const type=$("returnTargetType").value,items=type==="unit"?s.units:type==="relation"?s.relations:s.findings;$("returnTarget").innerHTML=items.map(x=>`<option value="${x.id}">${escapeHTML(x.unitCode||x.message||x.id)}</option>`).join("");$("remediationList").innerHTML=(s.remediationItems||[]).map(i=>`<div class="item"><div><strong>${escapeHTML(i.targetType)} · ${escapeHTML(i.targetId)}</strong><small>${escapeHTML(i.reason)} · ${i.closedAt?`已闭环${i.verifiedCheckRunId?"并复查":"，待复查"}`:"待整改"}${i.actualRevision?` · 实际修订 r${i.actualRevision}`:""}${i.resolutionNote?` · ${escapeHTML(i.resolutionNote)}`:""}</small></div>${!i.closedAt?`<button data-remediation-note="${i.id}">填写处理说明</button>`:""}</div>`).join("")}
function renderCredentials(s){$("credentialList").innerHTML=(s.credentials||[]).map(c=>`<div class="item"><div><strong>${escapeHTML(c.credentialId)}</strong><small>${c.status==="active"?"有效":"已撤销："+escapeHTML(c.revocationReason)}${c.replacementCredentialId?` · 替代：${escapeHTML(c.replacementCredentialId)}`:""}</small></div><div>${c.status==="active"?`<button data-revoke="${c.credentialId}">撤销</button>`:`<button data-reissue="${c.credentialId}" ${c.replacementCredentialId?"disabled":""}>补发</button>`}</div></div>`).join("")||"<p class='muted'>尚无凭据</p>"}
function renderAudit(s){$("auditList").innerHTML=s.audit.slice().reverse().map(a=>`<li><strong>${escapeHTML(a.summary)}</strong><small> · ${escapeHTML(a.actor)}</small><time>${new Date(a.occurredAt).toLocaleString()}</time></li>`).join("")}
function setActions(s){const mutable=["draft","remediation","returned"].includes(s.dossier.status);document.querySelectorAll("#unitForm button,#batchUnitForm button,#relationForm button,#checkButton").forEach(b=>b.disabled=!mutable);$("submitButton").disabled=!mutable;$("approveButton").disabled=s.dossier.status!=="pending_review";$("returnButton").disabled=s.dossier.status!=="pending_review";$("issueButton").disabled=s.dossier.status!=="frozen"}
function addBatchRow(){const row=$("batchUnitRows").rows.length+1;$("batchUnitRows").insertAdjacentHTML("beforeend",`<tr data-row="${row}"><td><input name="unitCode" required></td><td><input name="unitType" required></td><td><input name="description" required></td><td><input name="topElevation" type="number" step="0.01" required></td><td><input name="bottomElevation" type="number" step="0.01" required></td><td><input name="soilTraits" required></td><td><input name="photoRefs" required placeholder="逗号分隔"></td></tr>`)}
function resetBatch(){$("batchUnitRows").innerHTML="";addBatchRow();addBatchRow();$("batchErrors").textContent=""}
$("createForm").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.target);try{state.snapshot=await api("/api/v1/dossiers",{method:"POST",body:JSON.stringify({trenchCode:f.get("trenchCode"),excavationArea:f.get("excavationArea"),leadRecorder:f.get("leadRecorder"),chronologyHypothesis:f.get("chronologyHypothesis"),actor:f.get("leadRecorder"),idempotencyKey:key("create")})});e.target.reset();render();loadList();notify("探方案卷已创建")}catch(err){notify(err.message,true)}});
$("unitForm").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.target),id=f.get("unitID"),path=`/api/v1/dossiers/${state.snapshot.dossier.id}/units${id?`/${id}`:""}`;try{state.snapshot=await api(path,{method:id?"PUT":"POST",body:JSON.stringify(command({unitCode:f.get("unitCode"),unitType:f.get("unitType"),description:f.get("description"),topElevation:Number(f.get("topElevation")),bottomElevation:Number(f.get("bottomElevation")),soilTraits:f.get("soilTraits"),photoRefs:refs(f.get("photoRefs"))}))});e.target.reset();render();notify("单位修订已保存")}catch(err){notify(err.message,true)}});
$("batchUnitForm").addEventListener("submit",async e=>{e.preventDefault();const rows=[...$("batchUnitRows").rows].map((tr,index)=>{const value=name=>tr.querySelector(`[name='${name}']`).value;return{row:index+1,unitCode:value("unitCode"),unitType:value("unitType"),description:value("description"),topElevation:Number(value("topElevation")),bottomElevation:Number(value("bottomElevation")),soilTraits:value("soilTraits"),photoRefs:refs(value("photoRefs"))}});try{const result=await api(`/api/v1/dossiers/${state.snapshot.dossier.id}/units/batch`,{method:"POST",body:JSON.stringify(command({rows}))});state.snapshot=result.snapshot;resetBatch();render();notify(`整批保存成功：${result.items.map(i=>`第${i.row}行→${i.unitId}/r${i.revision}`).join("，")}`)}catch(err){$("batchErrors").innerHTML=(err.details||[]).map(d=>`<p>第 ${d.row||"-"} 行 ${escapeHTML(d.field)}：${escapeHTML(d.message)}</p>`).join("");notify(err.message,true)}});
$("relationForm").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.target),id=f.get("relationID"),path=`/api/v1/dossiers/${state.snapshot.dossier.id}/relations${id?`/${id}`:""}`;try{state.snapshot=await api(path,{method:id?"PUT":"POST",body:JSON.stringify(command({sourceUnitId:f.get("sourceUnitId"),targetUnitId:f.get("targetUnitId"),relationType:f.get("relationType"),evidenceNote:f.get("evidenceNote")}))});e.target.reset();render();notify("关系判定已保存")}catch(err){notify(err.message,true)}});
$("pathForm").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.target);try{const result=await api(`/api/v1/dossiers/${state.snapshot.dossier.id}/relation-path?sourceUnitId=${encodeURIComponent(f.get("sourceUnitId"))}&targetUnitId=${encodeURIComponent(f.get("targetUnitId"))}`);$("pathResult").innerHTML=`<p class="${result.conflict?"invalid":"valid"}">${pathName(result.classification)}${result.conflict?" · 存在冲突":""}</p><ol>${result.path.map(x=>`<li><a href="#" data-edit-relation="${x.relationId}">${escapeHTML(relationName(x.relationType))} · r${x.revision}</a>：${escapeHTML(x.evidenceNote)}</li>`).join("")}</ol>${result.conflictRelationIds.length?`<small>冲突关系：${escapeHTML(result.conflictRelationIds.join("、"))}</small>`:""}` }catch(err){notify(err.message,true)}});
$("checkButton").addEventListener("click",()=>act("checks",command(),"一致性检查已完成"));$("submitButton").addEventListener("click",()=>act("submit",command(),"已提交人工复核"));$("approveButton").addEventListener("click",()=>review(true));$("returnButton").addEventListener("click",()=>review(false));$("issueButton").addEventListener("click",()=>{const issuedBy=prompt("项目负责人姓名");if(issuedBy)act("credentials",command({actor:issuedBy,issuedBy}),"研究使用凭据已签发")});
async function act(endpoint,body,message){try{state.snapshot=await api(`/api/v1/dossiers/${state.snapshot.dossier.id}/${endpoint}`,{method:"POST",body:JSON.stringify(body)});render();notify(message)}catch(e){notify(e.message,true)}}
function checklist(){return Object.fromEntries([...document.querySelectorAll("#reviewChecklist input")].map(x=>[x.name,x.checked]))}
function review(approved){const reviewer=prompt("复核员姓名"),note=prompt(approved?"通过意见":"总体退回意见");if(!reviewer||!note)return;const targets=[];if(!approved){const reason=prompt("该定位对象的具体退回原因");if(!reason)return;targets.push({targetType:$("returnTargetType").value,targetId:$("returnTarget").value,reason})}act("review",command({actor:reviewer,approved,reviewer,note,checklist:checklist(),targets}),approved?"证据版本已冻结":"案卷已定向退回")}
$("verifyForm").addEventListener("submit",async e=>{e.preventDefault();try{const result=await api(`/api/v1/credentials/${new FormData(e.target).get("credentialID")}`);$("verification").innerHTML=`<p class="${result.valid?"valid":"invalid"}">${escapeHTML(result.message)}</p><small>摘要：${escapeHTML(result.credential.frozenManifestDigest)}${result.replacementCredentialId?` · 替代凭据：${escapeHTML(result.replacementCredentialId)}`:""} · 审计 ${result.audit.length} 条</small>`}catch(err){notify(err.message,true)}});
document.addEventListener("click",e=>{const open=e.target.dataset.open;if(open)openDossier(open);const uid=e.target.dataset.editUnit;if(uid){e.preventDefault();const u=state.snapshot.units.find(x=>x.id===uid),f=$("unitForm");Object.keys(u||{}).forEach(k=>{if(f.elements[k])f.elements[k].value=k==="photoRefs"?u[k].join(","):u[k]});if(u)scrollTo({top:f.offsetTop-20,behavior:"smooth"})}const rid=e.target.dataset.editRelation;if(rid){e.preventDefault();const r=state.snapshot.relations.find(x=>x.id===rid),f=$("relationForm");Object.keys(r||{}).forEach(k=>{if(f.elements[k])f.elements[k].value=r[k]});if(r)scrollTo({top:f.offsetTop-20,behavior:"smooth"})}const fid=e.target.dataset.resolve;if(fid){const note=prompt("请输入整改说明");if(note)api(`/api/v1/dossiers/${state.snapshot.dossier.id}/findings/${fid}`,{method:"PATCH",body:JSON.stringify(command({resolutionNote:note}))}).then(s=>{state.snapshot=s;render();notify("问题已关闭")}).catch(err=>notify(err.message,true))}const remediation=e.target.dataset.remediationNote;if(remediation){const note=prompt("请输入定向整改处理说明");if(note)api(`/api/v1/dossiers/${state.snapshot.dossier.id}/remediations/${remediation}`,{method:"PATCH",body:JSON.stringify(command({resolutionNote:note}))}).then(s=>{state.snapshot=s;render();notify("处理说明已记录，请重新执行检查")}).catch(err=>notify(err.message,true))}const revoke=e.target.dataset.revoke;if(revoke){const credential=state.snapshot.credentials.find(c=>c.credentialId===revoke),reason=prompt("撤销原因");if(reason)act(`credentials/${revoke}/revoke`,command({actor:credential.issuedBy,reason}),"凭据已撤销")}const reissue=e.target.dataset.reissue;if(reissue){const credential=state.snapshot.credentials.find(c=>c.credentialId===reissue);act(`credentials/${reissue}/reissue`,command({actor:credential.issuedBy}),"替代凭据已补发")}});
$("addBatchRow").addEventListener("click",addBatchRow);$("checkBatchSelect").addEventListener("change",()=>renderFindings(state.snapshot));$("changeFilter").addEventListener("change",()=>renderFindings(state.snapshot));$("severityFilter").addEventListener("change",()=>renderFindings(state.snapshot));$("returnTargetType").addEventListener("change",()=>renderReview(state.snapshot));$("refreshButton").addEventListener("click",loadList);
function refs(v){return String(v||"").split(",").map(x=>x.trim()).filter((x,i,a)=>x&&a.indexOf(x)===i)}function statusName(s){return{draft:"草拟",remediation:"整改中",pending_review:"待复核",returned:"已退回",frozen:"已冻结",issued:"已签发"}[s]||s}function relationName(s){return{overlies:"叠压",cuts:"打破",contemporary:"同期"}[s]||s}function changeName(s){return{added:"新增",persistent:"持续",resolved:"已消除"}[s]||s}function pathName(s){return{direct:"直接证据",transitive_mixed:"混合传递证据",unreachable:"不存在可达路径"}[s]||s}function escapeHTML(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
resetBatch();loadList();
